// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARBSrdqKeuhbvvIWh1xDDEscSqTNtrBGM',
    appId: '1:1082543396772:web:7b77c46e28218fc3d79331',
    messagingSenderId: '1082543396772',
    projectId: 'emart-2-c3f78',
    authDomain: 'emart-2-c3f78.firebaseapp.com',
    storageBucket: 'emart-2-c3f78.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1FAvX8EpMRZrtvLsayiXSd4j2-rbhtCI',
    appId: '1:1082543396772:android:3683878185e00310d79331',
    messagingSenderId: '1082543396772',
    projectId: 'emart-2-c3f78',
    storageBucket: 'emart-2-c3f78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSWup-t251-tbe03DBsP7UD5zX3W1Q5zs',
    appId: '1:1082543396772:ios:c77469e01b51a180d79331',
    messagingSenderId: '1082543396772',
    projectId: 'emart-2-c3f78',
    storageBucket: 'emart-2-c3f78.appspot.com',
    androidClientId: '1082543396772-o46fk4fr42vr7u5un0ulit9dm3itr54c.apps.googleusercontent.com',
    iosClientId: '1082543396772-ksh6hpuos9d97jcdosmv1vbmiiiartrf.apps.googleusercontent.com',
    iosBundleId: 'com.example.mycart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSWup-t251-tbe03DBsP7UD5zX3W1Q5zs',
    appId: '1:1082543396772:ios:c77469e01b51a180d79331',
    messagingSenderId: '1082543396772',
    projectId: 'emart-2-c3f78',
    storageBucket: 'emart-2-c3f78.appspot.com',
    androidClientId: '1082543396772-o46fk4fr42vr7u5un0ulit9dm3itr54c.apps.googleusercontent.com',
    iosClientId: '1082543396772-ksh6hpuos9d97jcdosmv1vbmiiiartrf.apps.googleusercontent.com',
    iosBundleId: 'com.example.mycart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbJXY-8JvXDyLfTrb-mW_RG_HMILsBd9A',
    appId: '1:1082543396772:web:cd5ee9ce39209b43d79331',
    messagingSenderId: '1082543396772',
    projectId: 'emart-2-c3f78',
    authDomain: 'emart-2-c3f78.firebaseapp.com',
    storageBucket: 'emart-2-c3f78.appspot.com',
  );
}
